### ISSUE TITLE
Using Github Projects for managing tasks

### ISSUE THREAD

**Issue by jaeyson** [mazarynio/mazaryn#16]
Hi! maybe we can use Github "Projects" for tracking our task(s), as `kanban` would be enough (or a start) for this project. What do you guys think?

Here's the example [board](https://github.com/orgs/mazarynio/projects/1/views/1) that's similar like trello. Feel free to remove it if we don't need.

**Comment by ioavv** [comment]
> Hi! maybe we can use Github "Projects" for tracking our task(s), as `kanban` would be enough (or a start) for this project. What do you guys think?
> 
> Here's the example [board](https://github.com/orgs/mazarynio/projects/1/views/1) that's similar like trello. Feel free to remove it if we don't need.

Great Idea, let's do
