### ISSUE TITLE
Like/Comments Post

### ISSUE THREAD

**Issue by ioavv** [mazarynio/mazaryn#33]
Creating Posts Works well but users aren't able to like and comments on Posts and also aren't able to see Who liked The Posts, The functions is done From Erlang and Elixir Clients So Devs can directly call like_post(userID, postID) from Clients and working on LiveView, same for Comments:  add_comment(author, postID, content)
get_all_comments(postID)
get_likes(likeID)

**Comment by pau-riosa** [comment]
Hi @jaeyson @ioavv is someone already working on this one? If none, I'll start working on this one.

**Comment by jaeyson** [comment]
@pau-riosa I haven't started yet.

**Comment by pau-riosa** [comment]
thank you @jaeyson
