### ISSUE TITLE
Fixing Issues & Improvments

### ISSUE THREAD

**Issue by ioavv** [mazarynio/mazaryn#82]
1. Searching Users Both on Homepage & Profile Page
2. Adding Emojis to Post and Chats
3. Verified account (approved Flag)
4. Warning message for Delete account on Profile 
5. Email Verification after sign up
6. Manage users independent page for Admins
7. Locale issues

**Comment by menty44** [comment]
- [x] Searching Users Both on Homepage & Profile Page
- [ ] Adding Emojis to Post and Chats
- [x] Verified account (approved Flag)
- [x] Warning message for Delete account on Profile
- [x] Email Verification after sign up
- [x] Manage users independent page for Admins
- [ ] Locale issues

**Comment by ioavv** [comment]
@menty44 Email verification isn't fixed yet!

**Comment by ioavv** [comment]
@menty44 The email verification stopped us from being login and redirect to homepage!
Please fix it!

**Comment by ioavv** [comment]
> * [x]  Searching Users Both on Homepage & Profile Page
> * [ ]  Adding Emojis to Post and Chats
> * [x]  Verified account (approved Flag)
> * [x]  Warning message for Delete account on Profile
> * [x]  Email Verification after sign up
> * [x]  Manage users independent page for Admins
> * [ ]  Locale issues

why you're not responding ?
the mail verifications is not done!!
